### ISSUE TITLE
why rxflowdemo has a black screen after launchScreen?

### ISSUE THREAD

**Issue by provswin** [RxSwiftCommunity/RxFlow#115] opened 2019-04-16 13:37 UTC
why rxflowdemo has a black screen after launchScreen?

in my project, I found there is a black screen after launchScreen, so I checked rxflowdemo and found same problem in the demo.

**Comment by provswin** [comment] 2019-04-18 09:50
@mumensh 
thanks for your reply, I am sure my configuration is right.

In demo, ```window.makeKeyAndVisible``` is setted after ```Flows.whenReady```.
I think, maybe ```Flows.whenReady(flow1: appFlow)``` took long time?  
During this time, we can only see a black screen.

```
        Flows.whenReady(flow1: appFlow) { root in
            window.rootViewController = root
            window.makeKeyAndVisible()
        }
```

**Comment by nexig** [comment] 2019-05-14 15:20
Hi Guys, have sam problem.
@provswin  could you show you appFlow class here? 
I checked it very carefully and I think the problem is not with Flows.whenReady that you show above, but with first step in AppFlow that you navigate. I predict that your root in appFlow is UINavigationController and it window is set correctly. The problem is with first viewController that will be present on your appFlow root. 
UIWindow set root ---> root willPresent UIViewController (long time and black screen) - > UIViewController presented.

**Comment by jorgelub12** [comment] 2019-12-12 14:54
Is there any workaround for this?

**Comment by SymBooler** [comment] 2020-05-04 03:34
same issue， anyone solved this problem？

**Comment by twittemb** [comment] 2020-05-05 00:49
Hi everyone,

This is the next thing on my todo list.

**Comment by twittemb** [comment] 2020-05-09 23:25
Hi everyone,

The black screen was due to way the bootstrap sequence was done. Coordination has to happen before the root of the window is set.
You can try this. It should fix your problem:

```
self.coordinator.coordinate(flow: appFlow, with: AppStepper(withServices: self.appServices))

Flows.whenReady(flow1: appFlow) { root in
    window.rootViewController = root
    window.makeKeyAndVisible()
}
```

**Comment by nexig** [comment] 2020-05-11 08:21
Hi @twittemb 

It work for Flows with NavigationController as root. But I have Flow with UITabBarController with 4 items and black screen still appear.

**Comment by SymBooler** [comment] 2020-05-13 17:50
Hi @twittemb, I get same issue as  @nexig.  my UITabBarController have 3 viewcontroller, [vc1, vc2, vc3]. If I call sleep(2) in vc1 function viewdidload, black screen lasts 2 seconds.
 Did you gays found solutions?

**Comment by twittemb** [comment] 2020-05-13 23:59
@nexig and @SymBooler can you share some code please ?

**Comment by twittemb** [comment] 2020-05-14 22:31
@SymBooler 

Basically RxFlow will wait for the flows to be ready (if you use Flows.whenReady to call the closure in Flows.whenReady. It means that all the flows/sub flows must have resolved their first step. It does not mean that it waits for the all the children VCs to be displayed before calling whenReady.

Waiting for 2s in the viewDidLoad will freeze the display even in a non RxFlow app.

**Comment by twittemb** [comment] 2020-05-16 19:20
@nexig, @SymBooler @jorgelub12, @provswin 

Could you give a try on the new branch -> https://github.com/RxSwiftCommunity/RxFlow/tree/feature/combine-flows

Flows.whenReady is deprecated on this branch.

There is new function:
```
Flows.use(flow1, flow2, ..., flowx, when: .created or .ready) { root1, root2, ..., rootx in
...
}
```

when passing .created, RxFlow won't wait for any step to be triggered before execution the block. The demo app has been updated to reflect that.

I'm really interested in your feedback.

Thanks.

**Comment by SymBooler** [comment] 2020-05-18 14:46
@twittemb Sorry for late. How could I give you the demo.
1. appDelegate
```swift
        let appFlow = AppFlow(withServices: self.appServices)
        self.coordinator.coordinate(flow: appFlow, with: AppStepper(withServices: self.appServices))
        Flows.whenReady(flow1: appFlow) { [unowned self] root in
            self.window?.rootViewController = root
            self.window?.makeKeyAndVisible()
        }
```
2. AppFlow
```swift
func navigateToMainBoard() -> FlowContributors {
        let schemeFlow = SchemeFlow(withServices: services)
        let contactsFlow = ContactsFlow(withServices: services)
        let billsFlow = BillsFlow(withServices: services)
        
        Flows.whenReady(flow1: schemeFlow, flow2: contactsFlow, flow3: billsFlow) { [unowned self] (root1: UINavigationController, root2: UINavigationController, root3: UINavigationController) in
            
            let config = UIImage.SymbolConfiguration(weight: .medium)
            var image = UIImage(systemName: "calendar.circle", withConfiguration: config)
            var selectedImage = UIImage(systemName: "calendar.circle.fill", withConfiguration: config)
            root1.tabBarItem = UITabBarItem(title: "日程", image: image, selectedImage: nil)
            
            image = UIImage(systemName: "rectangle.stack.person.crop", withConfiguration: config)
            selectedImage = UIImage(systemName: "rectangle.stack.person.crop.fill", withConfiguration: config)
            root2.tabBarItem = UITabBarItem(title: "联系人", image: image, selectedImage: selectedImage)
            
            image = UIImage(systemName: "pencil", withConfiguration: config)
            selectedImage = UIImage(systemName: "square.and.pencil", withConfiguration: config)
            root3.tabBarItem = UITabBarItem(title: "统计", image: image, selectedImage: selectedImage)
            self.rootViewController.selectedIndex = 0
            self.rootViewController.setViewControllers([root1, root2, root3], animated: false)
        }
        return .multiple(flowContributors: [.contribute(withNextPresentable: schemeFlow,
                                                        withNextStepper: OneStepper(withSingleStep: AppStep.schemeIsRequired)),
        
                                            .contribute(withNextPresentable: contactsFlow,
                                            withNextStepper: OneStepper(withSingleStep: AppStep.contactsAreRequired)),

                                            .contribute(withNextPresentable: billsFlow,
                                                        withNextStepper: OneStepper(withSingleStep: AppStep.billsAreRequired))])
    }
    
    func navigateToScheme() -> FlowContributors {
        
        let schemeFlow = SchemeFlow(withServices: services)            
        return .one(flowContributor: .contribute(withNextPresentable: schemeFlow, withNextStepper: OneStepper(withSingleStep: AppStep.schemeIsRequired), allowStepWhenNotPresented: false))
    }
    
    func navigateToContacts() -> FlowContributors {
        let contactsFlow = ContactsFlow(withServices: services)
        return .one(flowContributor: .contribute(withNextPresentable: contactsFlow, withNextStepper: OneStepper(withSingleStep: AppStep.contactsAreRequired), allowStepWhenNotPresented: false))
    }
    
    func navigateToBills() -> FlowContributors {
        let billsFlow = BillsFlow(withServices: services)
        return .one(flowContributor: .contribute(withNextPresentable: billsFlow, withNextStepper: OneStepper(withSingleStep: AppStep.billsAreRequired), allowStepWhenNotPresented: false))
    }

```
3.SchemeFlow
```swift
init(withServices services: AppServices) {
        self.services = services
    }
    
    private lazy var rootViewController: UINavigationController = {
        let viewController = UINavigationController()
        return viewController
    }()
    
    func navigate(to step: Step) -> FlowContributors {
        
        guard let step = step as? AppStep else { return .none }
        
        switch step {
        case .schemeIsRequired:
            return navigateToSchemeList()
        default:
            return .none
        }
    }
    
    func navigateToSchemeList() -> FlowContributors {
        let vc = SchemeViewController()
        self.rootViewController.pushViewController(vc, animated: false)
        return .none
    }
```

**Comment by SymBooler** [comment] 2020-05-19 11:34
@twittemb Hello，it's works when I use the [new branch]( https://github.com/RxSwiftCommunity/RxFlow/tree/feature/combine-flows)
**Could you tell me why i can't use ready?  I am confused!**
thank you.

**Comment by twittemb** [comment] 2020-05-20 00:46
Hi @SymBooler 

You can use either .created or .ready. Both are valid but I would say that for the app launch perhaps .created is more adapted since there will be no lag between flows creation and their display as the root.

**Comment by SymBooler** [comment] 2020-05-20 10:35
thanks for your help

**Comment by twittemb** [comment] 2020-05-29 00:22
Hi everyone.

May I close this issue after the release of the version 2.9.0 ?

**Closed** 2020-05-31 22:00 UTC

**Comment by nexig** [comment] 2020-07-09 11:04
@twittemb 

Black screen still appears in my app. Take a look on my code. I think problem could be with return .multiple() FlowContributors.

AppFlow
`Flows.use(dashboardFlow, when: .ready) { [unowned self] root  in
            self.window.rootViewController = root
            self.window.makeKeyAndVisible()
        }
        return .one(flowContributor: .contribute(withNextPresentable: dashboardFlow, withNextStepper: OneStepper(withSingleStep: WedMeStep.dashboardIsRequire)))`

DashboardFlow
`Flows.use(homeFlow, articleToolFlow, picturesFlow, offersFlow, when: .ready) { [unowned self] (root1, root2, root3, root4) in
            var viewControllers: [UIViewController] = []
            
            root1.tabBarItem = UITabBarItem(title: LoaderStrings.homeTabBarItem.localized, image: #imageLiteral(resourceName: "homeIcon"), tag: 0)
            viewControllers.append(root1)

            root2.tabBarItem = UITabBarItem(title: LoaderStrings.articlesAndTollsTabBarItem.localized, image: #imageLiteral(resourceName: "articlesIcon"), tag: 1)
            viewControllers.append(root2)
            self.articleToolFlow = articleToolFlow

            root3.tabBarItem = UITabBarItem(title: LoaderStrings.picturesTabBarItem.localized, image: #imageLiteral(resourceName: "imagesIcon"), tag: 2)
            viewControllers.append(root3)

            root4.tabBarItem = UITabBarItem(title: LoaderStrings.offersTabBarItem.localized, image: #imageLiteral(resourceName: "offersIcon"), tag: 3)
            viewControllers.append(root4)
            self.offerFlow = offersFlow
            
            self.rootViewController?.setViewControllers(viewControllers, animated: false)
        }
        return .multiple(flowContributors: [
            .contribute(withNextPresentable: articleToolFlow,
                       withNextStepper: OneStepper(withSingleStep: WedMeStep.articleToolIsRequire)),
            .contribute(withNextPresentable: picturesFlow,
                        withNextStepper: OneStepper(withSingleStep: WedMeStep.picturesIsRequire)),
            .contribute(withNextPresentable: homeFlow,
                        withNextStepper: OneStepper(withSingleStep: WedMeStep.homeIsRequire)),
            .contribute(withNextPresentable: offersFlow,
                        withNextStepper: OneStepper(withSingleStep: WedMeStep.offerIsRequire))
            ])`

**Comment by eleusiv3** [comment] 2021-10-29 22:53
@twittemb @nexig any updates on this? I also still get the black screen with uittabbarcontroller
