### ISSUE TITLE
`Flows.whenReady` not work.

### ISSUE THREAD

**Issue by PleaseDont** [RxSwiftCommunity/RxFlow#17] opened 2018-01-21 18:29 UTC
Here's my `MainFlow.swift`:

```swift
final class MainFlow: Flow {

  var root: UIViewController {
    return self.rootViewController
  }

  private let rootViewController: UITabBarController

  init() {
    self.rootViewController = UITabBarController().then {
      $0.tabBar.isTranslucent = false
      $0.tabBar.barTintColor = .rh_primary
    }
  }

  func navigate(to step: Step) -> [NextFlowItem] {
    guard let step = step as? AppStep else { return NextFlowItem.noNavigation }

    switch step {
    case .main:
      return navigationToMainScreen()
    default:
      return NextFlowItem.noNavigation
    }
  }

  private func navigationToMainScreen() -> [NextFlowItem] {

    let firstFlow = FirstFlow()
    let secondFlow = SecondFlow()
    let thirdFlow = ThirdFlow()
    let fourthFlow = FourthFlow()

    Flows.whenReady(flows: [firstFlow, secondFlow, thirdFlow, fourthFlow]) { roots in
      self.rootViewController.setViewControllers(
        roots.map { root in
          return (root as! UINavigationController).then {
            $0.navigationBar.isTranslucent = false
            $0.navigationBar.barTintColor = .rh_primary
          }
        },
        animated: false)

        // test the function works or not!
        print("whenReady")
    }

    return [
      NextFlowItem(nextPresentable: firstFlow, nextStepper: OneStepper(withSingleStep: AppStep.first)),
      NextFlowItem(nextPresentable: secondFlow, nextStepper: OneStepper(withSingleStep: AppStep.second)),
      NextFlowItem(nextPresentable: thirdFlow, nextStepper: OneStepper(withSingleStep: AppStep.third)),
      NextFlowItem(nextPresentable: fourthFlow, nextStepper: OneStepper(withSingleStep: AppStep.fourth))]
  }
}
```

And my `Podfile`:

```ruby
pod 'RxFlow', :git => 'https://github.com/RxSwiftCommunity/RxFlow.git', :branch => 'develop'
```

I found that the function `whenReady` is not work, and did not throw any errors. But when I change pods to `commit: c488cdd` like this:

```ruby
pod 'RxFlow', :git => 'https://github.com/RxSwiftCommunity/RxFlow.git', :commit => 'c488cdd'
```

While changing `NextFlowItem` to `Flowable`, `noNavigation` to `noFlow`, it just works fine, and the console print `whenReady`.

I have checked the source code, but not find the reason.

Help me, please.

**Comment by twittemb** [comment] 2018-01-21 19:54
Hi @PleaseDont 

I will take a look at that today. I will get back to you ASAP.

**Comment by twittemb** [comment] 2018-01-21 19:57
@PleaseDont 

The commit "c488cdd" is the last commit that works for you ? you tried a more recent one ?

**Comment by PleaseDont** [comment] 2018-01-21 20:53
@twittemb 
`d16e371` is OK, but not until `8c7123c`.

**Comment by twittemb** [comment] 2018-01-21 21:02
Can you give it another try on develop branch ? I just pushed a fix.

**Comment by PleaseDont** [comment] 2018-01-21 21:14
@twittemb 
Well, it works again, thank you so much.
I learned a lot reading your source code, you did a amazing job, thank you for that.
And I'm looking forward to new version 1.1.😊

**Comment by twittemb** [comment] 2018-01-21 21:15
@PleaseDont 

Cool, I'm glad to ear that. Sorry for the regression. This is the reason why I should write Unit Tests ... It will be my next task after V1.1

Bye.

**Closed by twittemb** 2018-01-21 21:15 UTC
Labels: bug

**Comment by twittemb** [comment] 2018-01-21 23:17
@PleaseDont 

Could you test your app with this branch -> feature/flattenSubscriptions

It is the next branch that I will merge in develop. As it performs some tricky refactoring in RxSwift subscription chains It would be nice if some (other than me) could give it a shot.

Thanks for your help.

**Comment by PleaseDont** [comment] 2018-01-22 03:12
@twittemb 
Sorry, I just saw this.
I have tested with `branch => feature/flattenSubscriptions`, it seems working well, nothing wrong.
