### ISSUE TITLE
flow deallocation when return .end on navigate(to:)

### ISSUE THREAD

**Issue by dmanuelcl** [RxSwiftCommunity/RxFlow#48] opened 2018-03-25 15:01 UTC
“Fatal error: Attempted to read an unowned reference but object 0x1c42d11e0 was already deallocated” is thrown when a child flow returns .end(withStepForParentFlow: step) on navigate(to:)

I have detected that the problem is caused by this line of code
```swift
self.delegate.endFlowCoordinator(withIdentifier: self.identifier)
```
In the following code snippet

<img width="1247" alt="captura de pantalla 2018-03-24 a la s 5 43 06 p m" src="https://user-images.githubusercontent.com/7545110/37876492-06ee2e16-301b-11e8-99af-c195ec843226.png">
The error is indicated in this line
<img width="957" alt="captura de pantalla 2018-03-24 a la s 5 41 36 p m" src="https://user-images.githubusercontent.com/7545110/37876491-04c845c2-301b-11e8-93ca-69c0ef3820b0.png">

What I understand is happening is that as you call
````swift
self.dismissFlow.onNext(Void ())
````
and immediately you call
```swift
self.delegate.endFlowCoordinator(withIdentifier: self.identifier)
```

The flow handled by the FlowCoordinator is deallocated in the latter so when the event is issued in dismissFlow the flow does not exist and therefore the error, the solution is to eliminate
```swift
122 self.delegate.endFlowCoordinator(withIdentifier: self.identifier)
```

Since it is also called in the subscription of dismissFlow
<img width="957" alt="captura de pantalla 2018-03-24 a la s 5 41 36 p m" src="https://user-images.githubusercontent.com/7545110/37876491-04c845c2-301b-11e8-93ca-69c0ef3820b0.png">

Apologies for my English

**Comment by twittemb** [comment] 2018-03-25 21:00
Hi @dmanuelcl 
Thanks for your feedback. 

Could you provide the code (both the parent and child flows) that causes this error please ?
The code seems to work fine in the Demo App and I'd like to be able to reproduce this issue easily so I can check your PR.

Thanks again.

**Comment by twittemb** [comment] 2018-03-25 21:55
Hi again.

I think your PR is a little bit too violent by commenting
```swift
self.delegate.endFlowCoordinator(withIdentifier: self.identifier)
```

because there are certain cases where the root ViewController of a Flow is not explicitly dismissed (see the Onboarding Flow of the demo app). So we have to explicitly unretain the FlowCoordinator by calling self.delegate.endFlowCoordinator(...)

I have just pushed a fix on develop.

Can you give it a try with your app and let me know if this fixes your issue.

Thanks.

**Comment by dmanuelcl** [comment] 2018-03-26 11:50
Hi @twittemb 

I think this solution can work, I'm going to try it on my project, thanks

**Comment by twittemb** [comment] 2018-03-26 12:52
Hi @dmanuelci

Thanks. I’m looking forward to hearing from you !

**Comment by dmanuelcl** [comment] 2018-03-30 13:44
Hi @twittemb, now is working thanks

**Closed** 2018-03-30 13:43 UTC
Labels: bug, resolved in develop

**Comment by El-Fitz** [comment] 2018-03-31 18:36
For some reason, I have the same issue on release 1.3.1
I just replaced all my .stepNotHandled with .end(withStepForParentFlow: step) after updating

What should I / can I do ?

**Comment by El-Fitz** [comment] 2018-04-02 16:42
So, this is the navigate(to step: Step)  function of the flow that is being dismissed:

	func navigate(to step: Step) -> NextFlowItems {
		guard let step = step as? SpotrStep else { return .none }
		
		switch step {
		case .search:
			return self.navigationToSearch()
		case .tagSelected(tag: let tag):
			return self.navigationToSpotsList(tag: tag)
		case .placeSelected(place: let place):
			return self.navigationToSpotsList(place: place)
		case .spotSelected(spot: let spot):
			return self.present(spot: spot)
		case .spotCardDone:
			return dismiss()
		case .dismiss:
			return self.rootViewController.presentedViewController == nil ? .end(withStepForParentFlow: spotrStep) : dismiss()
		case .back:
			return self.goBack()
		default:
			return .end(withStepForParentFlow: spotrStep)
		}
	}

it goes in the .dismiss case, returning .end(withStepForParentFlow: spotrStep), passing the step to the parent. This is the parent's navigate(to:) function:

	func navigate(to step: Step) -> NextFlowItems {
		guard let step = step as? SpotrStep else { return .none }
		
		switch step {
		case .tagsList:
			return navigationToTagsList()
		case .tagSelected(tag: let tag):
			return navigationToSpotsList(tag: tag)
		case .spotSelected(spot: let spot):
			return present(spot: spot)
		case .spotCardDone:
			return dismiss()
		case .profile(user: let user):
			return navigationToProfile(user: user)
		case .search:
			return navigationToSearch()
		case .searchDone:
			return self.navigate(to: SpotrStep.dismiss)
		case .login:
			return navigationToLoginScreen()
		case .loginDone:
			return self.navigate(to: SpotrStep.dismiss)
		case .dismiss:
			return dismiss()
		case .back:
			return goBack()
		default:
			return .end(withStepForParentFlow: spotrStep)
		}
	}

here again, dismiss case, calling the dismiss function below:

	func dismiss() -> NextFlowItems {
		rootViewController.presentedViewController?.dismiss(animated: true, completion: nil)
		return NextFlowItems.none
	}

And crashing with “Fatal error: Attempted to read an unowned reference but object 0x1c42d11e0 was already deallocated” somewhere along the way. I'm currently reverting to the latest RxFlow version to investigate where exactly it crashed in my code and will edit when it's done.

**Comment by El-Fitz** [comment] 2018-04-02 16:54
And now that I reimplemented it, it doesn't crash anymore. Guess there was something wrong with the way I did it before ? Damn. Thanks anyway ! :-)

**Comment by twittemb** [comment] 2018-04-02 16:56
Hi ... Glad all is fine !

Thanks for your feedback, it is always appreciated !

See ya !
