### ISSUE TITLE
Child controllers are never deallocated

### ISSUE THREAD

**Issue by claustrofob** [RxSwiftCommunity/RxFlow#181] opened 2021-12-10 16:37 UTC
If a flow contributor was initialised with `allowStepWhenDismissed: true` then all its immediate child controllers that provide flow contributors are never deallocated.

The bug is reproducible on RxFlowDemo as well:
1. In `DashboardFlow.navigateToDashboard()` set:
```
        return .multiple(flowContributors: [
            .contribute(
                withNextPresentable: wishListFlow,
                withNextStepper: CompositeStepper(steppers: [OneStepper(withSingleStep: DemoStep.moviesAreRequired), wishlistStepper]),
                allowStepWhenNotPresented: true,
                allowStepWhenDismissed: true
            ),
            .contribute(
                withNextPresentable: watchedFlow,
                withNextStepper: OneStepper(withSingleStep: DemoStep.moviesAreRequired),
                allowStepWhenNotPresented: true,
                allowStepWhenDismissed: true
            ),
            .contribute(
                withNextPresentable: trendingFlow,
                withNextStepper: trendingStepper,
                allowStepWhenNotPresented: true,
                allowStepWhenDismissed: true
            )
        ])
```
2. In app go to Wishlist -> Movie Details Screen. Then go back and verify that `MovieDetailViewController` was not deallocated.
3. Now in `WishlistFlow.navigateToMovieDetailScreen` change 
```
        return .one(
            flowContributor: .contribute(
                withNextPresentable: viewController,
                withNextStepper: viewController.viewModel
            )
        )
```  
to
```
return .none
```
4. Now repeat step 2 and verify that `MovieDetailViewController` is deallocated now.

**Comment by erginbilgin** [comment] 2021-12-22 11:52
Is there any update on this one? It seems to be the case for me too.

**Comment by sergs582** [comment] 2021-12-26 17:01
Same situation. Not deallocated VCs result in not disposed subscriptions

**Comment by twittemb** [comment] 2021-12-29 15:53
Hi,

Sorry for the late answer, I’ll try to take a look ASAP.

**Comment by leolobato** [comment] 2022-05-12 07:11
Any updates on this one? I can confirm I'm also running into this same issue.

**Comment by mgray88** [comment] 2023-06-09 18:03
Confirmed still exists in current version (2.13.0)

**Comment by mgray88** [comment] 2023-06-10 13:03
I can't say I've ever used this functionality and can't think of a use case for it. If anyone is able to provide a good use case I will look further into the issue.

Otherwise closing as wontfix

**Closed by mgray88** 2023-06-10 13:03 UTC
Labels: bug
